### ISSUE TITLE
Annual Corporate Registration

### ISSUE THREAD

**Issue by jmbrch4507** [counterpointhackers/documents#15]
Within 90 days of incorporation, each Georgia corporation must file an initial annual registration form that lists three principal officers with the Secretary of State. The fee is $50. Corporations that form between October 2 and December 31 must file the initial annual registration form between January 1 and April 1 of the next calendar year. Subsequent annual registrations are filed between January 1 and April 1 each year thereafter. The annual registration should be filed online at http://www.sos.ga.gov/Corporations/. Changes to the corporation’s address and/or registered agent and registered office address throughout the year are made by filing another annual registration and paying the $50 fee. A corporation that does not submit
its annual registration is subject to administrative dissolution. An administratively dissolved corporation may be reinstated within 5 years of the effective date of dissolution. There is a $250 fee to reinstate an
administratively dissolved corporation.

**Comment by tacksterwackster** [comment]
If planning to solicit funds in Georgia, submit the Charitable Organization Registration (Form C100) along with IRS Form 990 and a financial statement (both dated within 1 year of filing) to:
Office of the Secretary of State
Professional Licensing Boards & Securities Division
237 Coliseum Drive
Macon, GA 31217-3858
Information: (478) 207-2440
Web Site: sos.georgia.gov/securities/
Filing Fee: $35
Notes: 	If revenues over $0: Provide financial statement with Form C100.
If revenues over $500,000: Provide review audit with Form C100.
If revenues over $1,000,000: Provide complete audit with Form C100.

Educational institutions, religious organizations, organizations with total gross revenues of less than $25,000 in successive calendar years, and a limited number of other organizations may be exempt from this filing. For a complete list of qualified exemptions, refer to the web site listed above.

The Unified Registration Statement (URS) form may be filed in place of this application. This can be found at the following website: www.multistatefiling.org
