### ISSUE TITLE
501(c)(3)

### ISSUE THREAD

**Issue by jmbrch4507** [counterpointhackers/documents#17]
Note to nonprofit corporations that will pursue “tax exempt” status:
Nonprofit corporations are not automatically tax exempt under 501(c)(3) or other sections of the Internal Revenue Code by filing articles of incorporation with the Secretary of State. Nonprofit corporations must make an Application for Recognition of Exemption to the IRS for exempt status. Additional information to that required by the Georgia Nonprofit Corporation Code will be required in the articles of incorporation. Examples of such information are provided in IRS Publication 557. Said Publication, necessary applications, and other exemption information can be accessed at http://www.irs.ustreas.gov, or
by calling the IRS. The IRS information should be included in the articles of incorporation if tax exempt status will be sought by the nonprofit corporation. Otherwise, an amendment to articles, and a $20 filing
fee, will be required to add the material. IRS Publication 557 should be reviewed before incorporation if a nonprofit corporation wishes to be “tax exempt.”

**Comment by jmbrch4507** [comment]
http://www.irs.gov/pub/irs-pdf/p557.pdf

**Comment by tacksterwackster** [comment]
We have to do this at the state and federal level, correct?

**Comment by tacksterwackster** [comment]
To Obtain 501(c)(3) Tax-Exempt Status

Submit Form 1023, Application for Recognition of Exemption to:
Note new address:
Internal Revenue Service
P.O. Box 12192
Covington, KY 41012-0192
Information: (800) 829-1040
Forms: (800) 829-3676
Web Site: www.irs.gov/charities
Filing Fee: $850 ($400 for IRS Form 1023-EZ)

For more information on filing fees, see the IRS website.
Note: 	Certain organizations, including those with gross revenues at or below $50,000 annually, may qualify to file the online Form 1023-EZ, Streamlined Application for Recognition of Exemption. For more information and to determine if you are eligible for this form, refer to the IRS website.
