### ISSUE TITLE
appoint officers

### ISSUE THREAD

**Issue by tacksterwackster** [counterpointhackers/documents#2]
Board chair- If a chairman of the board of directors is elected, he or she shall preside at board meetings and shall exercise and perform such other powers and duties as the board may assign from time to time. If there is no president, the chairman of the board shall also be the chief executive officer and shall have the powers and duties of the president of the corporation set forth in these bylaws.

President-Subject to such supervisory powers as the board may give to the chairman of the board, if any, and subject to the control of the board, the president shall be the general manager of the corporation and shall supervise, direct, and control the corporation's activities, affairs, and officers. The president shall preside at all members' meetings and, in the absence of the chairman of the board, or if none, at all board meetings. The president shall have such other powers and duties as the board or the bylaws may require.

VP- If the president is absent or disabled, the vice presidents, if any, in order of their rank as fixed by the board, or, if not ranked, a vice president designated by the board, shall perform all duties of the president. When so acting, a vice president shall have all powers of and be subject to all restrictions on the president. The vice presidents shall have such other powers and perform such other duties as the board or the bylaws may require.

Secretary- The secretary shall keep or cause to be kept, at the corporation's principal office or such other place as the board may direct, a book of minutes of all meetings, proceedings, and actions of the board, of committees of the board, and of members' meetings. The minutes of meetings shall include the time and place that the meeting was held; whether the meeting was annual, general, or special, and, if special, how authorized; the notice given; the names of persons present at board and committee meetings; and the number of members present or represented at members' meetings. The secretary shall keep or cause to be kept, at the principal Georgia office, a copy of the articles of incorporation and bylaws, as amended to date. The secretary shall keep or cause to be kept, at the corporation's principal office or at a place determined by resolution of the board, a record of the corporation's members, showing each member's name, address, and class of membership. The secretary shall give, or cause to be given, notice of all meetings of members, of the board, and of committees of the board that these bylaws require to be given. The secretary shall keep the corporate seal, if any, in safe custody and shall have such other powers and perform such other duties as the board or the bylaws may require.

Treasurer- The chief financial officer shall keep and maintain, or cause to be kept and maintained, adequate and correct books and accounts of the corporation's properties and transactions. The chief financial officer shall send or cause to be given to the members and directors such financial statements and reports as are required to be given by law, by these bylaws, or by the board. The books of account shall be open to inspection by any director at all reasonable times.
The chief financial officer shall (i) deposit, or cause to be deposited, all money and other valuables in the name and to the credit of the corporation with such depositories as the board may designate; (ii) disburse the corporation's funds as the board may order; (iii) render to the president, chairman of the board, if any, and the board, when requested, an account of all transactions as chief financial officer and of the financial condition of the corporation; and (iv) have such other powers and perform such other duties as the board or the bylaws may require. If required by the board, the chief financial officer shall give the corporation a bond in the amount and with the surety or sureties specified by the board for faithful performance of the duties of the office and for restoration to the corporation of all of its books, papers, vouchers, money, and other property of every kind in the possession or under the control of the chief financial officer on his or her death, resignation, retirement, or removal from office.

**Comment by gordonwritescode** [comment]
@tachsterwackster can you paste in the "duties" of these when you get a chance?

**Comment by tacksterwackster** [comment]
@gordonwritescode added proposed duties of officers

**Comment by jmbrch4507** [comment]
Are we good to close this one out?

**Comment by gordonwritescode** [comment]
Yep yep.

Josh - Prezzy
Libby - Secretariat
Luke - Pennybags
