### ISSUE TITLE
create generic hold harmless agreement

### ISSUE THREAD

**Issue by jmbrch4507** [counterpointhackers/documents#4]

**Comment by gordonwritescode** [comment]
@jmbrch4507 is this only necessary if we are hosting events prior to incorporation?

**Comment by tacksterwackster** [comment]
@gordonwritescode I believe so.

**Comment by jmbrch4507** [comment]
Yeah, that was only intended to be used if we started doing classes before we get everything set up.  We'll need a full membership agreement that would include a hold harmless clause eventually.
