### ISSUE TITLE
Who should we bank with?

### ISSUE THREAD

**Issue by gordonwritescode** [counterpointhackers/documents#8]
Does anyone have any opinions on with whom we should bank? I am pretty opposed to BoA, Chase, and Wells. I wonder if there is a local Roswell Credit Union that does corp accounts.

**Comment by jmbrch4507** [comment]
I think a Credit Union would be best.  If Navy Federal wasn't so terrible at services and whatnot I would suggest them.  Not sure about any other ones though.
